---
roles:
  - src: pluggero.upgrade
    version: 1.1.0
  - src: pluggero.user_setup
    version: 2.5.0
  - src: pluggero.common_pkgs
    version: 2.0.0
  - src: pluggero.python
    version: 1.5.0
  - src: pluggero.virtualbox_guest
    version: 2.4.0
